/**
 * app/components/PolicyGeneratorDisplay.tsx
 *
 * Displays a generated AI policy with copy button, disclaimer,
 * remaining generation count, and limit warning banner.
 */

import type { ApiScanResponse } from "../lib/types";

interface PolicyGeneratorDisplayProps {
  generatedPolicy: ApiScanResponse["policy"] | null;
  policyRemaining: number | null;
  policyLimitMessage: string | null;
  onDismiss: () => void;
  onDismissLimit: () => void;
  onCopy: (text: string) => void;
}

export default function PolicyGeneratorDisplay({
  generatedPolicy,
  policyRemaining,
  policyLimitMessage,
  onDismiss,
  onDismissLimit,
  onCopy,
}: PolicyGeneratorDisplayProps) {
  return (
    <>
      {policyLimitMessage && (
        <s-section>
          <s-banner tone="warning">
            {policyLimitMessage}
            <button
              slot="actions"
              onClick={onDismissLimit}
              style={{
                fontSize: "13px",
                fontWeight: 600,
                color: "var(--p-color-text-subdued, #6d7175)",
                background: "none",
                border: "none",
                cursor: "pointer",
                textDecoration: "underline",
              }}
            >
              Dismiss
            </button>
          </s-banner>
        </s-section>
      )}

      {generatedPolicy && (
        <s-section>
          <s-card>
            <div style={{ padding: "4px 0" }}>
              <div
                style={{
                  display: "flex",
                  justifyContent: "space-between",
                  alignItems: "center",
                  marginBottom: "12px",
                }}
              >
                <div
                  style={{
                    fontSize: "18px",
                    fontWeight: 700,
                    color: "#0f172a",
                  }}
                >
                  Generated: {generatedPolicy.title}
                </div>
                <button
                  onClick={() => onCopy(generatedPolicy.body)}
                  style={{
                    fontSize: "13px",
                    fontWeight: 600,
                    color: "#0f172a",
                    background: "#f1f5f9",
                    border: "1px solid #cbd5e1",
                    borderRadius: "6px",
                    padding: "5px 12px",
                    cursor: "pointer",
                  }}
                >
                  Copy to Clipboard
                </button>
              </div>
              <div
                style={{
                  background: "#f8fafc",
                  border: "1px solid #e2e8f0",
                  borderRadius: "8px",
                  padding: "16px",
                  fontSize: "14px",
                  lineHeight: 1.6,
                  maxHeight: "400px",
                  overflowY: "auto",
                }}
                // Policy HTML is generated by our own Anthropic API call — trusted source
                dangerouslySetInnerHTML={{ __html: generatedPolicy.body }}
              />
              <div
                style={{
                  marginTop: "12px",
                  padding: "8px 12px",
                  background: "#fff5ea",
                  borderRadius: "6px",
                  fontSize: "12px",
                  color: "#92400e",
                  fontWeight: 600,
                }}
              >
                {generatedPolicy.disclaimer}
              </div>
              {policyRemaining != null && (
                <div
                  style={{
                    marginTop: "8px",
                    fontSize: "12px",
                    color: "#6d7175",
                  }}
                >
                  {policyRemaining} of 20 generations remaining this month
                </div>
              )}
              <div style={{ marginTop: "8px" }}>
                <button
                  onClick={onDismiss}
                  style={{
                    fontSize: "12px",
                    color: "#6d7175",
                    background: "none",
                    border: "none",
                    cursor: "pointer",
                    textDecoration: "underline",
                  }}
                >
                  Dismiss
                </button>
              </div>
            </div>
          </s-card>
        </s-section>
      )}
    </>
  );
}
