api_version = "2025-10"

[[extensions]]
name = "ShieldKit Product Schema"
handle = "json-ld-schema"
uid = "5f84566a-b42f-516d-7eec-00f7f6b2169e317fee21"
type = "theme"

  [[extensions.blocks]]
  name = "Product Schema (JSON-LD)"
  template = "blocks/product-schema.liquid"
  target = "body"

  [[extensions.blocks]]
  name = "Organization Schema (JSON-LD)"
  template = "blocks/organization-schema.liquid"
  target = "head"

  [[extensions.blocks]]
  name = "WebSite Schema (JSON-LD)"
  template = "blocks/website-schema.liquid"
  target = "head"
