// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/webhooks/app_subscriptions/update": {
    params: {};
  };
  "/webhooks/customers/data_request": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/webhooks/customers/redact": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/api/cron/weekly-scan": {
    params: {};
  };
  "/webhooks/shop/redact": {
    params: {};
  };
  "/sitemap.xml": {
    params: {};
  };
  "/robots.txt": {
    params: {};
  };
  "/blog": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/explainer": {
    params: {};
  };
  "/api/scan": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/scan": {
    params: {};
  };
  "/app": {
    params: {};
  };
  "/app/billing/confirm": {
    params: {};
  };
  "/app/dmca-takedowns": {
    params: {};
  };
  "/app/upgrade": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/webhooks/app_subscriptions/update" | "/webhooks/customers/data_request" | "/webhooks/app/scopes_update" | "/webhooks/customers/redact" | "/webhooks/app/uninstalled" | "/api/cron/weekly-scan" | "/webhooks/shop/redact" | "/sitemap.xml" | "/robots.txt" | "/blog" | "/auth/login" | "/blog/:slug" | "/explainer" | "/api/scan" | "/auth/*" | "/scan" | "/app" | "/app/billing/confirm" | "/app/dmca-takedowns" | "/app/upgrade";
  };
  "routes/webhooks.app_subscriptions.update.tsx": {
    id: "routes/webhooks.app_subscriptions.update";
    page: "/webhooks/app_subscriptions/update";
  };
  "routes/webhooks.customers.data_request.tsx": {
    id: "routes/webhooks.customers.data_request";
    page: "/webhooks/customers/data_request";
  };
  "routes/webhooks.app.scopes_update.tsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/webhooks.customers.redact.tsx": {
    id: "routes/webhooks.customers.redact";
    page: "/webhooks/customers/redact";
  };
  "routes/webhooks.app.uninstalled.tsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/api.cron.weekly-scan.ts": {
    id: "routes/api.cron.weekly-scan";
    page: "/api/cron/weekly-scan";
  };
  "routes/webhooks.shop.redact.tsx": {
    id: "routes/webhooks.shop.redact";
    page: "/webhooks/shop/redact";
  };
  "routes/sitemap[.]xml.tsx": {
    id: "routes/sitemap[.]xml";
    page: "/sitemap.xml";
  };
  "routes/robots[.]txt.tsx": {
    id: "routes/robots[.]txt";
    page: "/robots.txt";
  };
  "routes/blog._index.tsx": {
    id: "routes/blog._index";
    page: "/blog";
  };
  "routes/auth.login/route.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/blog.$slug.tsx": {
    id: "routes/blog.$slug";
    page: "/blog/:slug";
  };
  "routes/explainer.tsx": {
    id: "routes/explainer";
    page: "/explainer";
  };
  "routes/api.scan.ts": {
    id: "routes/api.scan";
    page: "/api/scan";
  };
  "routes/_index/route.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/auth.$.tsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/scan.tsx": {
    id: "routes/scan";
    page: "/scan";
  };
  "routes/app.tsx": {
    id: "routes/app";
    page: "/app" | "/app/billing/confirm" | "/app/dmca-takedowns" | "/app/upgrade";
  };
  "routes/app.billing.confirm.tsx": {
    id: "routes/app.billing.confirm";
    page: "/app/billing/confirm";
  };
  "routes/app.dmca-takedowns.tsx": {
    id: "routes/app.dmca-takedowns";
    page: "/app/dmca-takedowns";
  };
  "routes/app.upgrade.tsx": {
    id: "routes/app.upgrade";
    page: "/app/upgrade";
  };
  "routes/app._index.tsx": {
    id: "routes/app._index";
    page: "/app";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/webhooks.app_subscriptions.update": typeof import("./app/routes/webhooks.app_subscriptions.update.tsx");
  "routes/webhooks.customers.data_request": typeof import("./app/routes/webhooks.customers.data_request.tsx");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.tsx");
  "routes/webhooks.customers.redact": typeof import("./app/routes/webhooks.customers.redact.tsx");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.tsx");
  "routes/api.cron.weekly-scan": typeof import("./app/routes/api.cron.weekly-scan.ts");
  "routes/webhooks.shop.redact": typeof import("./app/routes/webhooks.shop.redact.tsx");
  "routes/sitemap[.]xml": typeof import("./app/routes/sitemap[.]xml.tsx");
  "routes/robots[.]txt": typeof import("./app/routes/robots[.]txt.tsx");
  "routes/blog._index": typeof import("./app/routes/blog._index.tsx");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.tsx");
  "routes/blog.$slug": typeof import("./app/routes/blog.$slug.tsx");
  "routes/explainer": typeof import("./app/routes/explainer.tsx");
  "routes/api.scan": typeof import("./app/routes/api.scan.ts");
  "routes/_index": typeof import("./app/routes/_index/route.tsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.tsx");
  "routes/scan": typeof import("./app/routes/scan.tsx");
  "routes/app": typeof import("./app/routes/app.tsx");
  "routes/app.billing.confirm": typeof import("./app/routes/app.billing.confirm.tsx");
  "routes/app.dmca-takedowns": typeof import("./app/routes/app.dmca-takedowns.tsx");
  "routes/app.upgrade": typeof import("./app/routes/app.upgrade.tsx");
  "routes/app._index": typeof import("./app/routes/app._index.tsx");
};